INTENTS: dict[str, list[str]] = {
    "check_balance": [
        "how much do I have",
        "wallet balance",
        "what's my balance",
        "show balance",
        "check balance",
        "how much money do I have",
        "funds available",
        "my balance",
    ],
    "send_payment": [
        "pay someone",
        "send money to",
        "transfer funds to",
        "pay maria",
        "send ten dollars to",
        "send payment",
        "make a payment",
        "pay for this",
        "send cash to",
    ],
    "query_wiki": [
        "look up",
        "what is",
        "tell me about",
        "search for",
        "find info on",
        "wiki jaguar",
        "look up jaguar",
        "what is a jaguar",
        "information about",
        "define this",
        "explain",
    ],
    "list_market": [
        "what's for sale",
        "show listings",
        "market list",
        "what can I buy",
        "show market",
        "available items",
        "browse market",
        "market items",
        "what is available",
    ],
    "buy_item": [
        "buy this",
        "I want to buy",
        "purchase this",
        "order item",
        "buy tomatoes",
        "I'll take it",
        "add to cart",
    ],
    "post_listing": [
        "sell something",
        "post a listing",
        "list item for sale",
        "add to market",
        "I want to sell",
        "put up for sale",
        "create listing",
    ],
    "list_nodes": [
        "who's online",
        "who is online",
        "active nodes",
        "show nodes",
        "who is on the mesh",
        "connected nodes",
        "list nodes",
        "nearby nodes",
        "node list",
        "who is around",
        "show all nodes",
        "nodes online",
        "list all nodes",
    ],
    "ping_node": [
        "ping node",
        "ping a specific node",
        "check if node reachable",
        "test connection to node",
        "can I reach that node",
        "is that node up",
        "ping address",
    ],
    "check_history": [
        "what did maria say",
        "show history",
        "message history",
        "past messages",
        "show my payments",
        "payment history",
        "transaction history",
        "what happened yesterday",
        "recent messages",
    ],
    "get_help": [
        "help",
        "what can you do",
        "list commands",
        "available commands",
        "show commands",
        "how do I use this",
        "what commands are there",
        "show help",
    ],
    "show_status": [
        "show status",
        "system status",
        "how is the mesh",
        "mesh status",
        "current status",
        "status report",
        "what's the status",
    ],
    "send_chat": [
        "say hello",
        "say good morning",
        "say good night",
        "say something",
        "send message",
        "send a message",
        "send good morning",
        "send hello",
        "send hi",
        "send gm",
        "broadcast to mesh",
        "broadcast message",
        "broadcast hello",
        "chat to the mesh",
        "tell the mesh",
        "tell everyone",
        "message the channel",
        "send to channel",
        "post to mesh",
        "shout out",
        "gm mesh",
        "good morning mesh",
    ],
    "open_config": [
        "open config",
        "open settings",
        "settings",
        "configure",
        "configuration",
        "change settings",
        "mqtt config",
        "mqtt settings",
        "set broker",
        "change broker",
        "set topic",
        "change topic",
        "broker settings",
        "network settings",
    ],
}
